let STORE_TYPE = {
    IS_LOADING: 'IS_LOADING',
    SHOW_NAV: 'SHOW_NAV',
    COMMON_PERMISSION: 'COMMON_PERMISSION',
    CHANNEL_LIST: 'CHANNEL_LIST',
    PROVINCE_LIST: 'PROVINCE_LIST',
    GROUP_LIST: 'GROUP_LIST',
    SHOW_SORT_DETAIL: 'SHOW_SORT_DETAIL',

    USER_INFO: 'USER_INFO',
    USER_CSRF_TOKEN: 'USER_CSRF_TOKEN',

    /*
		可视化档期-档期
    */
    SCHEDULE_PARAM: 'SCHEDULE_PARAM',
    SCHEDULE_PARAM_START: 'SCHEDULE_PARAM_START',
    SCHEDULE_DATA_INIT: 'SCHEDULE_DATA_INIT',
    SCHEDULE_DATA_TYPE: 'SCHEDULE_DATA_TYPE',
    SCHEDULE_DATA: 'SCHEDULE_DATA',
    SCHEDULE_APPENDDATA: 'SCHEDULE_APPENDDATA',
    SCHEDULE_SHOW_SORT_DETAIL: 'SCHEDULE_SHOW_SORT_DETAIL',
    /*
        可视化档期-商品
    */
    GOODS_PARAM: 'GOODS_PARAM',
    GOODS_PARAM_START: 'GOODS_PARAM_START',
    GOODS_DATA: 'GOODS_DATA',
    GOODS_APPENDDATA: 'GOODS_APPENDDATA',
    GOODS_DATA_INIT: 'GOODS_DATA_INIT',


    COMMON_BREADCRUMBS_UPDATE: 'common/breadcrumbs/update',

};
if (window && !window.STORE_TYPE) {
    window.STORE_TYPE = STORE_TYPE;
}
export default {
    STORE_TYPE
};