const structure = [{
        path: '/index',
        name: 'index',
        // redirect: '/scheduleList', //默认重定向跳转配置，暂时不开启 
        title: '首页',
        icon: 'fa-home',
        component: require('./../page/index/index.vue'),
        children: []
    }, {
        title: '可视化',
        icon: 'fa-eye',
        children: [{
            path: '/scheduleList',
            title: '档期列表',
            component: require('./../page/visual/schedule.vue'),
            icon: 'fa-tags',
            children: []
        }, {
            path: '/goodsList',
            title: '档期商品列表',
            component: require('./../page/visual/goods.vue'),
            icon: 'fa-shopping-bag',
            children: []
        }]
    }, {
        path: '/download',
        name: 'download',
        title: '登陆',
        icon: 'fa-home',
        component: require('./../page/other/download.vue'),
        children: []
    }, {
        path: '/messageCenter',
        name: 'messageCenter',
        title: '消息中心',
        icon: 'fa-home',
        component: require('./../page/other/messageCenter/index.vue'),
        children: []
    }, {
        path: '/summary',
        name: 'summary',
        title: '总览',
        icon: 'fa-home',
        component: require('./../page/other/summary/index.vue'),
        children: []
    }, {
        title: '推送管理',
        icon: 'fa-home',
        children: [{
            path: '/editor',
            name: 'editor',
            title: 'editor',
            icon: 'fa-home',
            component: require('./../page/other/pushCenter/editor.vue'),
            children: []
        },{
            path: '/appPush',
            name: 'appPush',
            title: 'app推送',
            icon: 'fa-home',
            component: require('./../page/other/pushCenter/appPush.vue'),
            children: []
        },{
            path: '/alipayPush',
            name: 'alipayPush',
            title: '支付宝推送',
            icon: 'fa-home',
            component: require('./../page/other/summary/index.vue'),
            children: []
        },{
            path: '/wecheatPush',
            name: 'wecheatPush',
            title: '微信推送',
            icon: 'fa-home',
            component: require('./../page/other/summary/index.vue'),
            children: []
        },{
            path: '/smsPush',
            name: 'smsPush',
            title: '短信推送',
            icon: 'fa-home',
            component: require('./../page/other/summary/index.vue'),
            children: []
        }, ]
    }, {
        title: '配置管理',
        icon: 'fa-home',
        children: [{
            title: '发送渠道管理',
            icon: 'fa-address-card-o',
            path: '/sendSetting',
            name: 'sendSetting',
            component: require('./../page/other/settingCenter/send.vue'),
            children: []
        }, {
            title: '接入渠道管理',
            icon: 'fa-address-card-o',
            path: '/connetSetting',
            name: 'connetSetting',
            component: require('./../page/other/settingCenter/connet.vue'),
            children: []
        }, {
            icon: 'fa-home',
            title: '重试机制',
            icon: 'fa-address-card-o',
            path: '/retrySetting',
            name: 'retrySetting',
            component: require('./../page/other/settingCenter/retry.vue'),
            children: []
        }, ]
    }, {
        title: '账户管理',
        icon: 'fa-cloud',
        children: [{
            title: '操作员管理',
            icon: 'fa-address-card-o',
            path: '/userCenter',
            name: 'userCenter',
            component: require('./../page/other/userCenter/list.vue'),
            children: [{
                path: '/addUser',
                name: 'addUser',
                title: '添加操作员账户',
                component: require('./../page/other/userCenter/add.vue'),
                children: []
            }, {
                path: '/userSetting/:id',
                name: 'userSetting',
                title: '权限管理',
                component: require('./../page/other/userCenter/list.vue'),
                children: []
            }]
        }, {
            title: '角色管理',
            icon: 'fa-id-badge',
            path: '/roleCenter',
            name: 'roleCenter',
            component: require('./../page/other/roleCenter/list.vue'),
            children: [{
                path: '/addRole',
                name: 'addRole',
                title: '添加角色',
                component: require('./../page/other/roleCenter/add.vue'),
                children: []
            }, {
                path: '/editRole/:id',
                name: 'editRole',
                title: '角色修改',
                component: require('./../page/other/roleCenter/edit.vue'),
                children: []
            }]
        }, {
            title: '修改密码',
            icon: 'fa-id-badge',
            path: '/changePassword',
            name: 'changePassword',
            component: require('./../page/other/userCenter/changePassword.vue'),
            children: []
        }, {
            title: '审核管理',
            icon: 'fa-id-badge',
            path: '/reviewManager',
            name: 'reviewManager',
            component: require('./../page/other/userCenter/reviewManager.vue'),
            children: []
        }, ]
    }, {
        path: '/queryPush',
        name: 'queryPush',
        title: '推送查询',
        icon: 'fa-home',
        component: require('./../page/other/queryPush/index.vue'),
        children: []
    }, {
        title: '推送数据统计',
        icon: 'fa-home',
        children: [{
            path: '/statisticApp',
            name: 'statisticApp',
            title: '中邮钱包',
            icon: 'fa-home',
            component: require('./../page/other/statisticCenter/app.vue'),
            children: []
        }, {
            path: '/statisticWecheat',
            name: 'statisticWecheat',
            title: '微信公众号',
            icon: 'fa-home',
            component: require('./../page/other/statisticCenter/weCheat.vue'),
            children: []
        }, {
            path: '/statisticAlipay',
            name: 'statisticAlipay',
            title: '支付宝',
            icon: 'fa-home',
            component: require('./../page/other/statisticCenter/alipay.vue'),
            children: []
        }, {
            path: '/statisticSms',
            name: 'statisticSms',
            title: '短信',
            icon: 'fa-home',
            component: require('./../page/other/statisticCenter/sms.vue'),
            children: []
        }]
    }, {
        path: '/groupCenter',
        name: 'groupCenter',
        title: '用户分组',
        icon: 'fa-home',
        component: require('./../page/other/groupCenter/list.vue'),
        children: [{
            path: '/groupAdd',
            name: 'groupAdd',
            title: '新建分组',
            component: require('./../page/other/groupCenter/add.vue'),
            children: []
        }, ]
    },

];

export default {
    structure: structure
};